name: Build image
on:
  workflow_dispatch:
    inputs:
      version:
        description: Which tool version to build
        required: true
        default: 8
        type: string

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: linux/arm/v7,linux/arm64/v8,linux/amd64
          build-args: |
            VERSION=${{inputs.version}}
          file: build/docker/Dockerfile
          tags: fearofcode/phpcov:${{inputs.version}}
